### PR TITLE
tools for handling text changes proposals and/or comments among co-authors

### PR DESCRIPTION
**Pull request by slowphil**
see the README

### CODE REVIEW

**Comment by mgubi** [comment]
great work @slowphil. I've only one comment: you can make it a plugin, so that one does not have to modify the my-init-texmacs.scm file to install it. See the lorem-ipsum plugin in tm-forge/miscellanea. You need to provide a init-my-plugin.scm file in your progs directory. Installation is simply to link the directory from ~/.TeXmacs/plugins. I'm using this method for many changes, it is very flexible and it is the method Joris designed to extend systematically TeXmacs. I think it is appropriate for your package.

**Comment by mgubi** [comment]
Also it would be useful to have an help page in TeXmacs format (beside that in the README) and maybe an example document.

**Comment by mgubi** [comment]
and please feel free to add a reference to this material in `tm-forge/miscellanea/README.md`

**Comment by slowphil** [comment]
Hmmm. Probably a stupid problem on my side but when I install plugins as you say, they do not seem to work.
For instance (supports-lorem-ipsum?) returns #f. This means the code was run, yet the plugin is not available. I also tried copying the  world plugin example to my plugins folder, with the same result. Even clearing my ~/.TeXmacs folder does not help. Any idea?

**Comment by woutersj** [comment]
I have noticed I sometimes need to do Tools->Update->Plugins to get plugins to appear, even after a restart. It's worth a try if you haven't already.

**Comment by slowphil** [comment]
> I have noticed I sometimes need to do Tools->Update->Plugins to get plugins to appear, even after a restart. It's worth a try if you haven't already.

Hey thanks that did the trick! Should be specified somewhere in the documentation relative to plugins. Right now in `plugin-simple.en.tm` you can read

> The configuration option :require specifies a condition which needs to be satisfied for the plug-in to be detected by TeXmacs [...]. The configuration is aborted if the requirement is not fulfilled.
Assuming that the configuration succeeds, the supports-world? predicate will evaluate to #t.

which is clearly not the whole truth.

**Comment by mgubi** [comment]
> I have noticed I sometimes need to do Tools->Update->Plugins to get plugins to appear, even after a restart. It's worth a try if you haven't already.

This is strange, since it is not my experience. As soon as I link symbolically the plugins into $TEXMACS_HOME_PATH/plugins it works. I think is important of course that the plugin name, the name of the directory and the name specify in the scheme commands coincide (but I'm not sure of that). Anyway we should indeed point out that some refreshing is needed. I've become aware of plugins used in this way only recently. They are quite powerful, as Joris says, you can hack almost on anything (including loading shared libraries to extend the C++ part). For example I'm preparing a plugin which add a bibliography mode.

**Comment by slowphil** [comment]
Yes, thanks both of you for enlightening me on this plugin configuration. It's really flexible and well-thought. 
I think the only thing missing is the possibility that a plugin provides its own tab to appear in the preference panel. I would have a use for that.

**Pull request merged**
