### PR TITLE
Standardization of doc

### PR DESCRIPTION
**Pull request by mdbenito**
This MR:

* Restructures the documentation so that it displays in the help
* Compress the png with pngquant (50%)
* Exports the abstract to README.md for consistency

**HOWEVER**: texmacs does **not** load the fontawesome package when building the documentation page, which results in icons not displaying 🤦🏽 Maybe it's a quick fix and we can merge anyway?

### CODE REVIEW

**Comment by mgubi** [comment]
What about other plugins which have style files (I think to the various computer algebra systems maybe)?

**Comment by mgubi** [comment]
A quick fix could be to run scheme to add by force the package in the document header if there is not already. Alternatively a less invasive approach is just to embed the necessary macros via an "include" in the preamble or somewhere else. I guess that given it is for documentation purposes, this would be fine.

**Comment by mdbenito** [comment]
I checked `tmdoc-include` and it would require a few changes to take into account the styles. Also, it might be a bad idea since that risks breaking the whole manual because of a misbehaved plugin.

So, following your suggestion, I used include for the style. Note that I actually had to use `include*`, because contrary to what the doc specifies, `include` is only for inclusions as part of projects (i.e. where documents are "parts" of a larger document) and doesn't work otherwise.

**Comment by mgubi** [comment]
Good enough for me. Thanks @mdbenito !

**Pull request merged**
