### PR TITLE
fix links to doc

### PR DESCRIPTION
**Pull request by slowphil**

### CODE REVIEW

**Comment by mgubi** [comment]
@slowphil  You should be able to merge it yourself now.

**Comment by slowphil** [comment]
Sorry, but there is no obvious way I can merge this PR. I can close it, but there is no Merge button. And the frame just above this comment I'm writing says  "This branch has no conflicts with the base branch. Only those with write access to this repository can merge pull requests." maybe hinting that I do not have such write access.

**Comment by mgubi** [comment]
I invited you as a member of the TeXmacs organisation. Did you received the invitation?

M

**Comment by slowphil** [comment]
Yes, I did. I accepted a couple of days ago and am now listed as a member of the organisation. Could it be that one has to be member when the PR is created?
Don't worry, merge it and we'll see next time.

**Comment by mgubi** [comment]
Let me fix this. I've now created a team to manage this repository and invited you to join in. You should have received an invitation and after accepting you should be able to merge yourself.

**Comment by slowphil** [comment]
Done! Thanks!

**Comment by slowphil** [comment]
BTW, I did not have to accept anything more and could merge right away.

**Pull request merged**
